[opener]

edit = [
  { run = 'nvim "$@"', block = true }
]
browser = [
  { run = "xdg-open \"$@\"", desc = "Open in default browser", orphan = true }
]

brave = [
  { run = "brave \"$@\"", desc = "Open in Brave", orphan = true }
]

default = [
  { run = "xdg-open \"$@\"", desc = "Open in default browser", orphan = true }
]

glow = [
  { run = 'glow "$@" | less -R', block = true, desc = "Render Markdown (glow)" }
]


[open]
prepend_rules = [
  { url = "*.md", use = [ "glow", "edit" ] },
  { url = "*.json", use = "edit" },
  { url = "*.html", use = [ "brave", "default", "edit" ] },
]



append_rules = [
  { url = "*", use = "my-fallback" },
]

[preview]
wrap = "yes"

[mgr]
ratio = [1, 2, 4]
show_hidden = false
sort_by = "natural"

